version: '3.8'

services:
  ytdlp-webui:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    environment:
      - DOWNLOAD_DIR=/app/downloads
      - CLEANUP_INTERVAL_HOURS=24
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

